<?php

declare(strict_types=1);

/**
 * Hardcoded scholarship data for the first backend pass.
 *
 * Later, replace this file with database queries while keeping the same keys
 * consumed by config/scholarship_backend.php and scholarship.php.
 */

return [
    'current_user' => [
        'id' => 'user_8321',
        'name' => 'Maya Rahman',
        'email' => 'maya@editorialscholar.test',
        'scholar_id' => '8321',
        'role' => 'Graduate Applicant',
        'country' => 'Bangladesh',
        'degree_level' => 'Masters',
        'field' => 'Public Policy',
        'gpa' => 3.88,
        'interests' => ['Public Policy', 'Ethics', 'International Relations'],
    ],

    'documents' => [
        ['id' => 'doc_cv', 'name' => 'Academic CV', 'type' => 'cv', 'status' => 'verified'],
        ['id' => 'doc_statement', 'name' => 'Personal Statement', 'type' => 'statement', 'status' => 'ready'],
        ['id' => 'doc_transcript', 'name' => 'Official Transcript', 'type' => 'transcript', 'status' => 'verified'],
        ['id' => 'doc_reference', 'name' => 'Reference Letters', 'type' => 'reference', 'status' => 'missing'],
    ],

    'tracked_grants' => [
        'gates-cambridge' => 'preparing',
        'marie-curie-fellowship' => 'watching',
    ],

    'scholarships' => [
        [
            'id' => 'rhodes-scholarship',
            'program' => 'Rhodes Trust',
            'title' => 'The Rhodes Scholarship',
            'region' => 'Global',
            'countries' => ['United Kingdom'],
            'institutions' => 'University of Oxford',
            'field' => 'All Disciplines',
            'fields' => ['All Disciplines'],
            'funding_type' => 'Full Funding',
            'deadline_label' => 'October 2, 2026',
            'deadline_date' => '2026-10-02',
            'amount' => 'Full tuition, stipend, travel',
            'duration' => '2-3 years',
            'level' => 'Postgraduate',
            'image' => 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?auto=format&fit=crop&w=900&q=80',
            'description' => 'A life-changing opportunity to study at the University of Oxford for outstanding leaders committed to public good.',
            'requirements' => ['cv', 'statement', 'transcript', 'reference'],
            'eligible_levels' => ['Masters', 'PhD'],
            'minimum_gpa' => 3.70,
            'tags' => ['Leadership', 'Oxford', 'Prestigious Selection'],
            'featured' => true,
        ],
        [
            'id' => 'fulbright-us-uk',
            'program' => 'Fulbright Program',
            'title' => 'US-UK Exchange Grant',
            'region' => 'North America',
            'countries' => ['United States', 'United Kingdom'],
            'institutions' => 'Ivy League Institutions, USA',
            'field' => 'All Disciplines',
            'fields' => ['All Disciplines'],
            'funding_type' => 'Full Funding',
            'deadline_label' => 'September 15, 2026',
            'deadline_date' => '2026-09-15',
            'amount' => 'Tuition support plus living stipend',
            'duration' => '1 academic year',
            'level' => 'Graduate',
            'image' => 'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=900&q=80',
            'description' => 'A competitive cultural and academic exchange grant for scholars preparing for international research leadership.',
            'requirements' => ['cv', 'statement', 'transcript', 'reference'],
            'eligible_levels' => ['Masters', 'PhD'],
            'minimum_gpa' => 3.50,
            'tags' => ['Exchange', 'Research', 'Leadership'],
        ],
        [
            'id' => 'erasmus-ethics',
            'program' => 'Erasmus Mundus',
            'title' => 'Joint Master in Ethics',
            'region' => 'Europe',
            'countries' => ['France', 'Belgium'],
            'institutions' => 'Sorbonne, Paris & KU Leuven',
            'field' => 'Ethics',
            'fields' => ['Ethics', 'Philosophy', 'Public Policy'],
            'funding_type' => 'Full Funding',
            'deadline_label' => 'January 8, 2027',
            'deadline_date' => '2027-01-08',
            'amount' => 'Tuition waiver, mobility grant, stipend',
            'duration' => '24 months',
            'level' => 'Masters',
            'image' => 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=900&q=80',
            'description' => 'A joint European master route for students focused on ethics, governance, and policy across multiple campuses.',
            'requirements' => ['cv', 'statement', 'transcript'],
            'eligible_levels' => ['Masters'],
            'minimum_gpa' => 3.30,
            'tags' => ['Joint Degree', 'Europe', 'Mobility'],
        ],
        [
            'id' => 'gates-cambridge',
            'program' => 'Gates Cambridge',
            'title' => 'Gates Cambridge Scholarship',
            'region' => 'Europe',
            'countries' => ['United Kingdom'],
            'institutions' => 'University of Cambridge',
            'field' => 'All Disciplines',
            'fields' => ['All Disciplines'],
            'funding_type' => 'Full Funding',
            'deadline_label' => 'December 3, 2026',
            'deadline_date' => '2026-12-03',
            'amount' => 'Full study cost and discretionary funding',
            'duration' => 'Program length',
            'level' => 'Postgraduate',
            'image' => 'https://images.unsplash.com/photo-1564981797816-1043664bf78d?auto=format&fit=crop&w=900&q=80',
            'description' => 'A highly selective scholarship for postgraduate study at Cambridge with emphasis on social leadership.',
            'requirements' => ['cv', 'statement', 'transcript', 'reference'],
            'eligible_levels' => ['Masters', 'PhD'],
            'minimum_gpa' => 3.60,
            'tags' => ['Cambridge', 'Leadership', 'Global Impact'],
        ],
        [
            'id' => 'marie-curie-fellowship',
            'program' => 'Marie Sklodowska-Curie Actions',
            'title' => 'Marie Curie Fellowship',
            'region' => 'Europe',
            'countries' => ['European Union'],
            'institutions' => 'EU Host Institutions',
            'field' => 'Research',
            'fields' => ['Research', 'Public Policy', 'Ethics'],
            'funding_type' => 'Research Grant',
            'deadline_label' => 'November 20, 2026',
            'deadline_date' => '2026-11-20',
            'amount' => 'Research allowance, salary, mobility support',
            'duration' => '12-36 months',
            'level' => 'Doctoral/Postdoctoral',
            'image' => 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=900&q=80',
            'description' => 'A European research mobility fellowship for researchers building international and interdisciplinary projects.',
            'requirements' => ['cv', 'statement', 'reference'],
            'eligible_levels' => ['PhD'],
            'minimum_gpa' => 3.50,
            'tags' => ['Research', 'Mobility', 'EU'],
        ],
        [
            'id' => 'chevening-scholarship',
            'program' => 'Chevening',
            'title' => 'Chevening Scholarship',
            'region' => 'Global',
            'countries' => ['United Kingdom'],
            'institutions' => 'UK Universities',
            'field' => 'Leadership & Policy',
            'fields' => ['Public Policy', 'International Relations', 'All Disciplines'],
            'funding_type' => 'Full Funding',
            'deadline_label' => 'August 25, 2026',
            'deadline_date' => '2026-08-25',
            'amount' => 'Tuition, monthly stipend, travel costs',
            'duration' => '1 year',
            'level' => 'Masters',
            'image' => 'https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=900&q=80',
            'description' => 'A UK government scholarship for emerging leaders pursuing a one-year master degree in the United Kingdom.',
            'requirements' => ['cv', 'statement', 'transcript'],
            'eligible_levels' => ['Masters'],
            'minimum_gpa' => 3.20,
            'tags' => ['Leadership', 'UK', 'Policy'],
        ],
    ],

    'mentors' => [
        [
            'name' => 'Dr. Helena Moore',
            'focus' => 'Oxford personal statement review',
            'availability' => '2 slots this week',
        ],
        [
            'name' => 'Samir Chowdhury',
            'focus' => 'Policy fellowship interview coaching',
            'availability' => 'Next available Monday',
        ],
    ],

    'testimonial' => [
        'quote' => "The Editorial Scholar did not just find me a scholarship; they helped me frame my academic narrative for the Rhodes committee.",
        'name' => 'Elena Rodriguez',
        'title' => "Rhodes Scholar '23",
    ],
];

